[versions]
plugin-android = "7.2.2"
plugin-kotlin = "1.8.10"

kotlinx-coroutines = "1.6.4"

littlekt = "0.7.0.934cda7-SNAPSHOT"

[libraries]
plugin-android = { module = "com.android.tools.build:gradle", version.ref = "plugin-android" }
plugin-kotlin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "plugin-kotlin" }

kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
littlekt-core = { module = "com.lehaine.littlekt:core", version.ref = "littlekt" }

[bundles]
plugins = ["plugin-android", "plugin-kotlin"]
